# Generated by Django 4.2 on 2023-05-10 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_category_alter_review_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='products_category',
        ),
    ]
